module Galtersufia
  module GenericFile
    module InvenioResourceTypeMappings
      extend ActiveSupport::Concern

      # Mapping of DigitalHub resource type to IRDM specific resource type
      # for dh categories that map to multiple IRDM categories ";" is used to delimit
      # TODO: Resource types with semi-colon delimited values do not map directly to an invenio type and will need to
      # be mapped later when a type is decided on
      DH_RESOURCE_TYPES = {
        "Abstracts": "Abstract; Meeting Abstract",
        "Academic Dissertations":	"Bachelor Thesis; Masters Thesis; Doctoral Thesis",
        "Account Books": "Account Book",
        "Addresses": "Address (Speech)",
        "Advertisements": "Other",
        "Animation": "Animation",
        "Annual Reports": "Report",
        "Architectural Drawings": "Architectural Drawing",
        "Article":"Journal article;  Newspaper Article; Other Article",
        "Audio Visual Document": "Video; Sound (Recording)",
        "Bibliography":	"Bibliography",
        "Biobibliography": "Biobibliography",
        "Biography": "Biography; Personal Narrative; Diary",
        "Blogs": "Social Media Posting",
        "Case Reports": "Case Report",
        "Catalogs": "Catalog",
        "Clinical Trial": "Clinical Trial",
        "Collected Correspondence": "Collection; Correspondence",
        "Conference Proceeding": "Conference Proceeding",
        "Congresses": "Congress",
        "Dataset": "Dataset",
        "Dictionary": "Book",
        "Drawings": "Drawing",
        "Editorial Article": "Journal article, Editorial",
        "Electronic Supplementary Materials": "Chart; Table; Dataset; Bibliography; Technical Documentation",
        "Ephemera": "Ephemera",
        "Evaluation Studies": "Evaluation Study",
        "Examination Questions": "Examination Questions",
        "Exhibitions": "Exhibition",
        "Fictional Works": "Fictional Work",
        "Forms": "Form",
        "Guideline": "Guideline; Study Design",
        "Handbooks": "Handbook",
        "Historical Article": "Other Article",
        "Image": "Pictorial Work, Photograph",
        "Introductory Journal Article": "Journal Article; Other Article",
        "Journal Article": "Journal Article",
        "Journal": "Journal",
        "Lecture Notes": "Lecture Notes",
        "Lectures": "Lecture",
        "Lecture": "Letter; Correspondence",
        "Manuscript": "Manuscript; Preprint",
        "Maps": "Map",
        "Masters Thesis": "Masters Thesis",
        "Meeting Abstracts": "Meeting Abstract",
        "News": "News; Newsletter",
        "Other": "Other; Other Article",
        "Periodicals": "Magazine; Newsletter",
        "Photographs": "Photograph",
        "Pictorial Works": "Pictorial Work",
        "Poetry": "Poetry",
        "Portraits": "Portrait",
        "Postcards": "Postcard",
        "Poster": "Conference Poster; Other",
        "Presentation": "Presentation",
        "Programmed Instruction": "Presentation",
        "Programs": "Program",
        "Project": "", #TODO: Check with Sara if this is necessary. According to note from box csv file there are only
                       # two projects one that is private and one for the collection
        "Report": "Report",
        "Research Paper": "Report; Review; Other Article",
        "Resource Guides": "Resource Guide",
        "Review": "Review",
        "Software or Program Code ": "Other; Software; Technical Documentation",
        "Speech": "Lecture; Presentation; Sound (Recording)",
        "Statistics": "Statistics",
        "Study Design": "Study Design",
        "Tables": "Table",
        "Technical Report": "Technical Documentation",
      }.with_indifferent_access

      # Mapping of IRDM sub type / specific resource type to IRDM resource type / category
      IRDM_RESOURCE_TYPES = {
        "Collection": "Archival Items",
        "Ephemera": "Archival Items",
        "Exhibition": "Archival Items",
        # "Physical Object": "Archival Items",
        # "Book Review": "Articles",
        # "Data Paper": "Articles",
        "Editorial": "Articles",
        "Journal Article": "Articles",
        "Newspaper Article": "Articles",
        "Other Article": "Articles",
        # "Retraction of Publication": "Articles",
        "Review": "Articles",
        # "Software Paper": "Articles",
        "Account Book": "Books",
        # "Atlas": "Books",
        "Biography": "Books",
        "Book": "Books",
        # "Book Part": "Books",
        "Catalog": "Books",
        "Diary": "Books",
        "Handbook": "Books",
        # "Conference Paper": "Conference Objects",
        "Conference Poster": "Conference Objects",
        "Conference Proceeding": "Conference Objects",
        "Congress": "Conference Objects",
        "Meeting Abstract": "Conference Objects",
        "Dataset": "Dataset",
        "Architectural Drawing": "Images",
        "Chart": "Images",
        "Drawing": "Images",
        "Map": "Images",
        "Photograph": "Images",
        "Pictorial Work": "Images",
        "Portrait": "Images",
        "Examination Questions": "Learning Objects",
        "Lecture": "Learning Objects",
        "Lecture Notes": "Learning Objects",
        # "Lesson Plan": "Learning Objects",
        "Presentation": "Learning Objects",
        # "Problems and Exercises": "Learning Objects",
        # "Syllabus": "Learning Objects",
        "Animation": "Multimedia",
        # "Database": "Multimedia",
        "Postcard": "Multimedia",
        "Social Media Posting": "Multimedia",
        "Software": "Multimedia",
        "Sound (Recording)": "Multimedia",
        "Video": "Multimedia",
        # "Website": "Multimedia",
        # "Interview": "Other",
        # "Laboratory Manual": "Other",
        "News": "Other",
        "Other": "Other",
        "Table": "Other",
        "Journal": "Periodicals",
        "Magazine": "Periodicals",
        "Newsletter": "Periodicals",
        # "Newspaper": "Periodicals",
        "Case Report": "Study Documentation",
        # "Clinical Study": "Study Documentation",
        "Clinical Trial": "Study Documentation",
        # "Comparative Study": "Study Documentation",
        "Data Management Plan": "Study Documentation",
        "Evaluation Study": "Study Documentation",
        # "Measurements and Tests": "Study Documentation",
        # "Research Proposal": "Study Documentation",
        "Statistics": "Study Documentation",
        "Study Design": "Study Documentation",
        "Abstract": "Text Resources",
        "Address (Speech)": "Text Resources",
        "Bibliography": "Text Resources",
        "Biobibliography": "Text Resources",
        # "Comment": "Text Resources",
        "Correspondence": "Text Resources",
        "Fictional Work": "Text Resources",
        "Form": "Text Resources",
        "Guideline": "Text Resources",
        "Letter": "Text Resources",
        "Manuscript": "Text Resources",
        # "Patent": "Text Resources",
        # "Patient Education Handout": "Text Resources",
        "Personal Narrative": "Text Resources",
        "Poetry": "Text Resources",
        "Preprint": "Text Resources",
        "Program": "Text Resources",
        "Report": "Text Resources",
        "Resource Guide": "Text Resources",
        "Technical Documentation": "Text Resources",
        # "Working Paper": "Text Resources",
        "Bachelor Thesis": "Theses and Dissertations",
        "Doctoral Thesis": "Theses and Dissertations",
        "Masters Thesis": "Theses and Dissertations"
      }.with_indifferent_access
    end
  end
end

