module Galtersufia
  module GenericFile
    module InvenioResourceTypeMappings
      extend ActiveSupport::Concern

      # Mapping of DigitalHub resource type to IRDM specific resource type
      DH_IRDM_RESOURCE_TYPES = {
        "Abstracts": ["text", "text-abstract"],
        "Academic Dissertations": ["thesis", "thesis-bachelor_thesis"],
        "Account Books": ["book", "book-account_book"],
        "Addresses": ["text", "text-speech"],
        "Advertisements": ["other", "other-other"],
        "Animation": ["multimedia", "multimedia-animation"],
        "Annual Reports": ["text", "text-report"],
        "Architectural Drawings": ["image", "image-architectural_drawing"],
        "Article": ["article", "article-journal_article"],
        "Audio Visual Document": ["multimedia", "multimedia-video"],
        "Bibliography": ["text", "text-bibliography"],
        "Biobibliography": ["text", "text-biobibliography"],
        "Biography": ["book", "book-biography"],
        "Blogs": ["multimedia", "multimedia-social_media"],
        "Case Reports": ["study_documentation", "study_documentation-case_report"],
        "Catalogs": ["book", "book-catalog"],
        "Clinical Trial": ["study_documentation", "study_documentation-clinical_trial"],
        "Collected Correspondence": ["archival", "archival-collection"],
        "Conference Proceeding": ["conference", "conference-conference_proceeding"],
        "Congresses": ["conference", "conference-congress"],
        "Dataset": ["dataset"],
        "Dictionary": ["book", "book-book"],
        "Drawings": ["image", "image-drawing"],
        "Editorial Article": ["article", "article-journal_article"],
        "Electronic Supplementary Materials": ["image", "image-chart"],
        "Ephemera": ["archival", "archival-ephemera"],
        "Evaluation Studies": ["study_documentation", "study_documentation-evaluation_study"],
        "Examination Questions": ["learning", "learning-examination_questions"],
        "Exhibitions": ["archival", "archival-exhibition"],
        "Fictional Works": ["text", "text-fictional_work"],
        "Forms": ["text", "text-form"],
        "Guideboooks": ["book", "book-book"],
        "Guideline": ["text", "text-guideline"],
        "Handbooks": ["book", "book-handbook"],
        "Historical Article": ["article", "article-other_article"],
        "Image": ["image", "image-pictorial_work"],
        "Introductory Journal Article": ["article", "article-journal_article"],
        "Journal Article": ["article", "article-journal_article"],
        "Journal": ["periodical", "periodical-journal"],
        "Lecture Notes": ["learning", "learning-lecture_notes"],
        "Lectures": ["learning", "learning-lecture"],
        "Letter": ["text", "text-letter"],
        "Manuscript": ["text", "text-manuscript"],
        "Maps": ["image", "image-map"],
        "Masters Thesis": ["thesis", "thesis-masters_thesis"],
        "Meeting Abstracts": ["conferencet", "conference-meeting_abstract"],
        "News": ["other", "other-news"],
        "Other": ["other", "other-other"],
        "Periodicals": ["periodical", "periodical-magazine"],
        "Photographs": ["image", "image-photograph"],
        "Pictorial Works": ["image", "image-pictorial_work"],
        "Poetry": ["text", "text-poetry"],
        "Portraits": ["image", "image-portrait"],
        "Postcards": ["multimedia", "multimedia-postcard"],
        "Poster": ["conference", "conference-conference_poster"],
        "Presentation": ["conference", "conference-conference_presentation"],
        "Programmed Instruction": ["learning", "learning-presentation"],
        "Programs": ["text", "text-program"],
        "Report": ["text", "text-report"],
        "Research Paper": ["text", "text-report"],
        "Resource Guides": ["text", "text-resource_guide"],
        "Review": ["article", "article-review"],
        "Software or Program Code": ["other", "other-other"],
        "Speech": ["learning", "learning-lecture"],
        "Statistics": ["study_documentation", "study_documentation-statistics"],
        "Study Design": ["study_documentation", "study_documentation-study_design"],
        "Tables": ["other", "other-table"],
        "Technical Report": ["text", "text-technical_documentation"],
      }.with_indifferent_access
    end
  end
end
